CREATE TABLE
    USERS (
        ID SERIAL PRIMARY KEY,
        NAME VARCHAR(50) NOT NULL,
        EMAIL VARCHAR(50),
        PASSWORD VARCHAR(100),
        CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        STATUS CHAR(1)
    );